### ISSUE TITLE
Mouse locking does not work

### ISSUE THREAD

**Issue by perelowski** [caiiiycuk/js-dos.com#63]
Hello,

Following up on my "Civilization" project here: https://zmozgu.net/civ.html

I wanted to enable mouse locking feature. I have followed the documentation and modified my static HTML file to create the "dosbox.conf" and pass the "autolock=true" into it. 

Weird thing happens - the OS cursor does not disappear after clicking and there is a position difference between the OS cursor and DOS cursor, that is visible in the game area - the further you move the OS cursor to the sides, the bigger the distance between it and the DOS cursor becomes. 

You can check it by yourself - you have to wait until the game intro ends and the DOS cursor can be visible.

What am I doing wrong?

My code is below:

```
<body>
  <canvas id="jsdos"></canvas>
  <script>
    Dos(document.getElementById("jsdos"), {
        wdosboxUrl: "https://js-dos.com/6.22/current/wdosbox.js"
    }).ready((fs, main) => {

	fs.createFile("dosbox.conf", `
            [sdl]
            autolock=true
        `);

      fs.extract("civ.zip").then(() => {
        main(["-conf", "dosbox.conf", "-c", "cd civ1", "-c", "CIV.EXE"])
      });
    });
  </script>
</body>

</html>
```

**Comment by caiiiycuk** [comment]
Yes, you right. The mouse does not work in locked/fulscreen mode. This is long living bug, and I still hope to fix it. But it's not clear how to fix it properly.

**Comment by perelowski** [comment]
Thanks for your reply. I can see that the locked mode does not work at all. The cursor does not 
"blend" into DOS window after it's being clicked. Is it also a bug?

**Comment by ZaDarkSide** [comment]
Will this ever be fixed? On Emularity works just fine:
https://github.com/db48x/emularity

Here is an example with Emularity:
https://emupedia.net/beta/emuos/vfat/apps/dosbox/index.html?game=15

And here is an example with JS-DOS:
https://emupedia.net/beta/emuos/vfat/apps/dosbox/index.html?gamev2=arkanoid

**Comment by caiiiycuk** [comment]
Thanks for good point. I faced problem that it works very different for some game, e.g. I can fix it for arkanoid but it will break other game. Btw, I will try to look what I can do again.

**Comment by caiiiycuk** [comment]
@perelowski @ZaDarkSide 
Just refactored pointer lock system, please try latest version 
https://github.com/caiiiycuk/js-dos/releases/tag/6.22.34
It should fix this issue. You need to set autolock=true to lock mousepointer. Like this:
https://js-dos.com/#js-dos-622-faq-mouse-locking

**Comment by ZaDarkSide** [comment]
It's still not working for me properly, are you sure you pushed the right files to npm?
Because `wdosbox.wasm.js` from `dist` folder from the npm package seems unchanged.
Full path: `node_modules/js-dos/dist/wdosbox.wasm.js`.

Anyway on Chrome latest works only the first time, then if you press Escape and then click again the canvas it will no longer pointer lock the mouse.
I also get an error on Chrome: `Assertion failed: Bitu(event->key.keysym.sym)<keys, at: ../dreamlayers-em-dosbox-em-dosbox-svn-sdl2/src/gui/sdl_mapper.cpp,563,CheckEvent`

On Firefox latest there is no change, it's not working at all.

Strangely pressing the `Fullscreen` button you can see that it will properly fullscreen the canvas and will automatically pointer lock the mouse. I use this piece of code to go to fullscreen: `Module.requestFullscreen(true, false);`

You can test here: https://emupedia.net/beta/emuos/vfat/apps/dosbox/index.html?gamev2=arkanoid

**Comment by caiiiycuk** [comment]
I see it works only once. Btw, for me your link also captures mouse in FF. Anyway emscripte pointer lock api does not work in my case, I will ask in emscripten group why so, and then decide how to fix it.

**Comment by ZaDarkSide** [comment]
I'm using Firefox Quantum version 69.0.3 (64-bit) can you test on this version too?
And why pressing the `Fullscreen` button everything works as expected and not when not in fullscreen?
The button is in the upper right corner, you can test here: https://emupedia.net/beta/emuos/vfat/apps/dosbox/index.html?gamev2=arkanoid

**Comment by caiiiycuk** [comment]
It works for Qunatum 69.0.2 (only first time as in chrome). But, error that you report exists (even if it works for fullscreen).

My code does not receive pointer lock state updates from emscripten api. E.g. dosbox ask to lock the mouse, then browser should inform dosbox that pointer is locked, but this never happens (even if pointer actually locked). But when you request fullscreen, something happen and this info delivered to dosbox everything start working.

 I need to fix it properly. I believe that something goes wrong in emscripten code.
https://groups.google.com/forum/#!topic/emscripten-discuss/CNxCC0ZiUzc

I believe that fix will be ready until end of week. Pls be patient.

**Comment by ZaDarkSide** [comment]
Yes, sure I'm patient, no pressure, if there is anything I can help you with just tell me.

**Comment by caiiiycuk** [comment]
https://github.com/emscripten-core/emscripten/issues/9681

**Comment by caiiiycuk** [comment]
@ZaDarkSide  please test 6.22.36 it should works now

**Comment by ZaDarkSide** [comment]
For Chrome 78.0.3904.70 (64-bit) it works every time and seems to be fixed.

For Firefox 70.0 (64-bit) it works almost every time and sometimes it needs 2 clicks to capture the mouse pointer.

But for both browsers in fullscreen it doesn't captures the mouse anymore.

You can test here: https://emupedia.net/beta/emuos/vfat/apps/dosbox/index.html?gamev2=arkanoid

**Comment by astigmatism** [comment]
I can also confirm the above.

Additionally, it looks like there is no longer any mouse movement in fullscreen regardless of the autolock setting (being true or false)

**Comment by caiiiycuk** [comment]
I am not recommend to use `Module.requestFullscreen`, it's absolute as I know. Please update to 6.22.37 and use `fullscreen` method form command interface.
http://js-dos.com/#js-dos-622-faq-fullscreen

**Comment by caiiiycuk** [comment]
it works for me in all cases chrome/ff | autolock(on/off)

**Comment by ZaDarkSide** [comment]
You are right the fullscreen and pointer locking it's now working for me too in version 6.22.37 with `window.ci.fullscreen();` instead of `Module.requestFullscreen(true, false);`

Apart of the small issue in Firefox when you get this error `Request for pointer lock was denied because the document is not focused.`  and you must click twice to capture the mouse, everything works as expected. (this happens if you load the html in an iframe)

You can test here: https://emupedia.net/beta/emuos/vfat/apps/dosbox/index.html?gamev2=arkanoid

Well this issue should be closed now.

**Comment by perelowski** [comment]
Hello! I have tested the new version of js-dos on yet another game - Panzer General:
https://zmozgu.net/pg.html
...and found another interesting behavior. If you click on the game canvas just after it starts, during title screens - when mouse cursor gets locked, the DOS game cursor will always jump to the top of the game canvas after every click. 

If you wait with the cursor 'outside' until the DOS game cursor appears on the screen, then click on the game canvas, it will work properly in the game.

This behaviour happens in Chrome 78 and in Firefox 70. In Safari 13 it works fine (all tested on Mac)

**Comment by ZaDarkSide** [comment]
> 
> 
> Hello! I have tested the new version of js-dos on yet another game - Panzer General:
> https://zmozgu.net/pg.html
> ...and found another interesting behavior. If you click on the game canvas just after it starts, during title screens, when mouse cursor gets locked, the DOS game cursor will always jump to the top of the game canvas after every click.
> 
> If you wait with the cursor 'outside' until the DOS game cursor appears on the screen, then click on the game canvas, it will work properly in the game.
> 
> This behaviour happens in in Chrome 78 and in Firefox 70. In Safari 13 it works fine (all tested on Mac)

I could replicate this behavior also.

**Comment by caiiiycuk** [comment]
@perelowski moved to #73
